### ISSUE TITLE
Add topic: dspace

### ISSUE THREAD

**Issue by katrinleinweber** [cstarcher/pysaf#2]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/dspace](https://github.com/topics/dspace), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by cstarcher** [comment]
Thanks for the suggestion! I'll do that.

**Comment by katrinleinweber** [comment]
Merci :-)
